CREATE TABLE bodyparts (
   language varchar(32) NOT NULL PRIMARY KEY,
   ankle varchar(64),
   arm varchar(64),
   armpit varchar(64),
   back varchar(64),
   backside varchar(64),
   beard varchar(64),
   belly varchar(64),
   bellybutton varchar(64),
   stomach varchar(64),
   blood varchar(64),
   body varchar(64),
   bodyback varchar(64),
   bone varchar(64),
   bottom varchar(64),
   
   calf varchar(64),
   cheek varchar(64),
   chest varchar(64),
   chin varchar(64),
   ear varchar(64),
   elbow varchar(64),
   
   eye varchar(64),
   eyebrow varchar(64),
   eyelash varchar(64),
   face varchar(64),
   foot varchar(64),
   forehead varchar(64),
   hair varchar(64),
   hand varchar(64),
   heart varchar(64),
   hip varchar(64),
   intestines varchar(64),
   kidney varchar(64),
   knee varchar(64),
   leg varchar(64),
   mouth varchar(64),
   neck varchar(64),
   nose varchar(64),
   nostril varchar(64),
   shin varchar(64),
   shoulder varchar(64),
   skin varchar(64),
   teeth varchar(64),
   thigh varchar(64),
   thumb varchar(64),
   toe varchar(64),
   tongue varchar(64),
   tooth varchar(64),
   waist varchar(64),
   wrist varchar(64),
   finger varchar(64),
   head varchar(64),
   lips varchar(64));



INSERT into bodyparts VALUES  ('english','Ankle','Arm','Armpit','Back','Backside','Beard','Belly','Bellybutton','Stomach','Blood','Body','bodyback','Bone','Bottom','Calf','Cheek','Chest','Chin','Ear','Elbow','Eye','Eyebrow','Eyelash','Face','foot','Forehead','Hair','Hand','Heart','Hip','Intestines','Kidney','Knee','Leg','Mouth','Neck','Nose','Nostril','Shin','Shoulder','Skin','Teeth','Thigh','Thumb','Toes','Tongue','Tooth','Waist','Wrist','Finger','Head','lips');

INSERT into bodyparts VALUES ("butchulla",NULL,"gining",NULL,NULL,NULL,NULL,"boo-loo",NULL,NULL,"gakki",NULL,NULL,NULL,"gundar",NULL,NULL,NULL,"yikkal","binang","gundi","miil",NULL,NULL,NULL,"djinang",NULL,"dala","biri",NULL,"ganim",NULL,NULL,"djeemee or burruu","djerang","djang'ga","ganna","mooroo",NULL,NULL,"waalil","gubar","nyiling","djerang",NULL,"birri-dhinang","djunam",NULL,NULL,NULL,"bi","gam","dhambur");	INSERT into bodyparts VALUES ("dharumbal","wul","marra",NULL,NULL,NULL,NULL,"banna","guana",NULL,"guma","gabal",NULL,"rillu","bunthi and mulla",NULL,NULL,"ngamba","anu","binang","gulgul","dili","dinan",NULL,"wutha","dina","yali","manam","malla","dalgu","yuli",NULL,"rindu","bikal","dumu and gal","dangga","bimbi","nunta","yuna",NULL,"nirrgal","nhuman","yira","dharha","murrgin","dalgayu","dalang",NULL,NULL,"dandha","balngnan","ngatha","munu");	INSERT into bodyparts VALUES ("duungidjawu",NULL,"Gining",NULL,NULL,NULL,NULL,NULL,NULL,"Muu","Diyir","Djam",NULL,"Giira",NULL,NULL,NULL,NULL,NULL,"Binung","Gulumur","Miya",NULL,NULL,"Nguwar","Dinung","Yiyim","Kabui","Wadangir / Djunim",NULL,NULL,NULL,NULL,"Buhn","Djangar","Dambur","Wanda","Mii",NULL,"Buyu","Walir","Bem","Diyeng",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Bii","Maa",NULL);	INSERT into bodyparts VALUES ("pronunciation__duungidjawu",NULL,"Gin-ing",NULL,NULL,NULL,NULL,NULL,NULL,"Moo","Dee-year","Jarm",NULL,"Geer-ah",NULL,NULL,NULL,NULL,NULL,"Bin-ung","Goo-loom-or","Mii-ya",NULL,NULL,"Noo-wah","Din-nung","Yii-im","Kar-boo-ee","Wah-dun-ear / Jun-eem",NULL,NULL,NULL,NULL,"Boon","Jar-nah","Darm-boor","Wan-dar","Mee",NULL,"Boo-yoo","Wah-leer","Beam","Dee-ang",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Bee","Mah",NULL);	INSERT into bodyparts VALUES ("gooreng_gooreng","wugul","gini",NULL,NULL,NULL,NULL,"bulu","wogoo",NULL,"dii",NULL,NULL,"daigil","mundi",NULL,NULL,NULL,"yinboo","bina","goomoo","mil","teeping",NULL,"gun gun","djina",NULL,"gubu","biru","dulgu","gaman",NULL,NULL,"bii","djanyar","geem","wandal","muru",NULL,NULL,"gilun","yulan","dira",NULL,NULL,"mundoie","dunga",NULL,NULL,NULL,NULL,"wurul","yillim");	INSERT into bodyparts VALUES ("gunggari","Bargu","Do-roo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Bullkoo","Yarrun","Bunthi",NULL,NULL,"Wonka","Nuthung","Munga","Uraldo","Dilli",NULL,NULL,NULL,"Din-ar","Bulka","Utha","Murrda","Yulgoo",NULL,NULL,NULL,"Moogoo","Bala","Da","Nulldo","Who",NULL,NULL,"Bidda",NULL,"Illa",NULL,NULL,"Munn-dooe","Thullung",NULL,NULL,NULL,"Mum boo","Doonka","Bikki");	INSERT into bodyparts VALUES ("kala_kawaw_ya","danakuku","geth",NULL,NULL,NULL,NULL,"maytha","maythakup",NULL,"kulka","gamu",NULL,"ridh","kup",NULL,NULL,"da","ibu","kawra (singular) kawral ( plural)","kudu","purka (sg) purkal (pl)","boeybasam",NULL,"paru","san","poewth","yalbup","geth","ngoenakap","pasikap",NULL,"pulipul","kulu","ngar","gud","mudul","piti","koerab",NULL,"thabay","goengaw","dhang (sg) dhangal (pl)","dokap","kuyku dhimur","sanaw dhimur(sg) sanaw dhimural (pl)","noey",NULL,NULL,"pertha","dhimur(sg) dhimural(pl)","kuyk","iragud");	INSERT into bodyparts VALUES ("ku_ku_yalanji",NULL,"daki",NULL,NULL,NULL,NULL,"waral",NULL,NULL,"ju-ju",NULL,NULL,NULL,"bun-ni",NULL,NULL,"du-mu","bari","milka","juril","myil","nyinki",NULL,"walu","jina","munju","malka-bu",NULL,"wudal","waba",NULL,"ngun-gum-urr",NULL,NULL,"ngan-dal","jakay",NULL,NULL,NULL,"binda","yulban","ditha",NULL,"mula","durra","nyabil",NULL,NULL,"jinbar","mara","dukul","yimbi");	INSERT into bodyparts VALUES ("nggerikudi",NULL,"d'aga",NULL,NULL,NULL,NULL,"ra",NULL,NULL,NULL,"mboa",NULL,NULL,NULL,NULL,NULL,"oni","engau","wo'a","muto","adae","b'ada",NULL,NULL,"goa","bai","nga",NULL,NULL,NULL,NULL,NULL,NULL,"tena",NULL,NULL,NULL,NULL,NULL,"daru","kaie","abau",NULL,NULL,NULL,"puduna",NULL,NULL,NULL,"a","troka","enga");	INSERT into bodyparts VALUES ("nggerrikwidhi",NULL,"d'aga",NULL,NULL,NULL,NULL,"ra",NULL,NULL,NULL,"mboa",NULL,NULL,NULL,NULL,NULL,"oni","engau","wo'a","muto","adae","b'ada",NULL,NULL,"goa","bai","nga",NULL,NULL,NULL,NULL,NULL,NULL,"tena",NULL,NULL,NULL,NULL,NULL,"daru","kaie","abau",NULL,NULL,NULL,"puduna",NULL,NULL,NULL,"a","troka","enga");	INSERT into bodyparts VALUES ("turubul",NULL,"Yamma",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Gardin",NULL,NULL,"Dyrrbin",NULL,NULL,NULL,NULL,NULL,"Binung",NULL,"Mill",NULL,NULL,NULL,"Dinung","Yilim","Kabui","Marra",NULL,NULL,NULL,NULL,"Buhn","Dharang","Dhambur","Durdur","Muro",NULL,"Buyu","Giga",NULL,"Deea",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Gillen","Magul",NULL);	INSERT into bodyparts VALUES ("pronunciation__turubul",NULL,"Yah-mah",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Gar-din",NULL,NULL,"Deer-bin",NULL,NULL,NULL,NULL,NULL,"Bin-ung",NULL,"Mill",NULL,NULL,NULL,"Din-nung","Yill-im","Kar-boo-ee","Mah-rah",NULL,NULL,NULL,NULL,"Boon","Dah-rang","Dam-boor","Door-door","Moo-row",NULL,"Boo-yoo","Gee-gah",NULL,"Dee-ah",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Gill-een","Mah-gool",NULL);	INSERT into bodyparts VALUES ("wakka_wakka","Wulu","Gining","Wamgir","Burum","Mundi","Yikka",NULL,NULL,"Mu","Dir",NULL,NULL,"Gira",NULL,"Buyu","Wanga",NULL,"Yikka","Binang","Kulumur","Ma","Dhipin","Buel-buel","Ngwar","Djinang",NULL,"Gam","Na","Du",NULL,"Gunang",NULL,"Bundur","Djangar","Dhambur","Wanda","Mi",NULL,NULL,"Wali","Dumee","Diang","Djungor",NULL,"Djinang","Dunam",NULL,NULL,NULL,"Gillin","Mau","Dhambur");	INSERT into bodyparts VALUES ("pronunciation__wakka_wakka","Woo-loo","Geen-inn","Warm-gear","Boo-rum","Moon-dee","Yick-ah",NULL,NULL,"Moo","De-ah",NULL,NULL,"Gear-ah",NULL,"Boo-yoo","Won-ah",NULL,"Yick-ah","Bin-ung","Kool-oo-moor","Mah","Dee-pin","Bewl-bewl","Ing-wah","Gin-ung",NULL,"Gam","Nah","Doo",NULL,"Goon-un",NULL,"Boon-door","Jun-gar","Dum-burr","Wun-dah","Mee",NULL,NULL,"Wah-lee","Doo-mee","Dee-ung","Jung-or",NULL,"Gin-ung","Doo-nam",NULL,NULL,NULL,"Gill-lin","Maw","Dum-burr");	INSERT into bodyparts VALUES ("warrgamay",NULL,"Garrgal",NULL,NULL,NULL,NULL,"Yulgu","Djuulndjuruɲ",NULL,"Gurrmal","Gambara",NULL,"Djulgil","Djulu",NULL,NULL,"Djindi","Ngangul","Bina","Mugay","Gayga","Buyin",NULL,"Ngaɲi","Bigaɲ","Rimbi","Murray","Mala","Rulgu","Bilu",NULL,"Djagarri","Bunggu","Djarrawaga","Ngayilnggarra","Wudu",NULL,"Binda",NULL,"Yunggu","Yirra","Djarra","Gumbi","Ɲigiɲ","Djalaɲ",NULL,NULL,NULL,NULL,NULL,"Mugal","Mulin");	INSERT into bodyparts VALUES ("yugambeh","Wulu","Gungil",NULL,NULL,NULL,NULL,"Muhng",NULL,NULL,"Gumera","Biyu",NULL,"Darigan","Gumu",NULL,NULL,"Tumerrigunn","Yarany","Binang","Kuruhny","Mih","Ngihlim",NULL,"Nugal","Jinang","Ngihr","Guhr","Danggan","Dulgu","Wayan",NULL,"Munggar","Kindil","Jarang","Jeyang","Jalayn","Muru",NULL,NULL,"Walagan",NULL,"Jirang","Jarang","Danggan",NULL,"Jurgung",NULL,NULL,NULL,"Danggan","Bawur","Jehng");	INSERT into bodyparts VALUES ("pronunciation__yugambeh","Woo-loo","Gun-gill",NULL,NULL,NULL,NULL,"Mun",NULL,NULL,"Goo-mer-ah","Bee-you",NULL,"Dah-ree-gan","Goo-moo",NULL,NULL,"Tum-air-ee-gun","Yah-run","Bin-ung","Koo-run","Mee","Nill-im",NULL,"Noo-gull","Gee-nung","Near","Gurr","Dung-gan","Dull-goo","Way-un",NULL,"Mung-gah","Kin-dill","Jah-rung","Jee-young","Jay-lun","Moo-roo",NULL,NULL,"Wal-ah-gun",NULL,"Gee-rung","Jah-rung","Dung-gan",NULL,"Jur-gun",NULL,NULL,NULL,"Dung-gan","Bah-war","Jen");	INSERT into bodyparts VALUES ("yugarabul",NULL,"Yamma",NULL,NULL,NULL,NULL,NULL,"Dhiggeri",NULL,NULL,NULL,NULL,"Dyrrbin",NULL,NULL,NULL,NULL,NULL,"Binung",NULL,"Mil",NULL,NULL,NULL,"Dinna","Midgeree",NULL,"Marra",NULL,NULL,NULL,NULL,"Buhn","Mungurra","Dhamburu","Ngullun","Muru",NULL,"Buyu","Giga",NULL,"Deear",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Killen","Mugil",NULL);	INSERT into bodyparts VALUES ("pronunciation__yugarabul",NULL,"Yah-mah",NULL,NULL,NULL,NULL,NULL,"Dig-ah-ree",NULL,NULL,NULL,NULL,"Deer-bin",NULL,NULL,NULL,NULL,NULL,"Bin-ung",NULL,"Meel",NULL,NULL,NULL,"Din-nah","Midge-ah-ree",NULL,"Mah-rah",NULL,NULL,NULL,NULL,"Boon","Mun-gah-rah","Dam-boo-roo","Noo-lun","Moo-roo",NULL,"Boo-yoo","Gee-gah",NULL,"Dee-ah",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Kill-een","Moo-gill",NULL);	INSERT into bodyparts VALUES ("yuggera",NULL,"Waiyebba",NULL,NULL,NULL,NULL,NULL,"Dhiggeri",NULL,NULL,NULL,NULL,"Dyrrbin",NULL,NULL,NULL,NULL,NULL,"Binung",NULL,"Mil",NULL,NULL,NULL,"Dinna","Yilam",NULL,"Marra",NULL,NULL,NULL,NULL,"Buhn","Dharang","Dhambur","Nggurrun","Muru",NULL,"Buyu","Giga",NULL,"Deear",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Killen","Gahm",NULL);	INSERT into bodyparts VALUES ("pronunciation__yuggera",NULL,"Way-yeb-bah",NULL,NULL,NULL,NULL,NULL,"Dig-ah-ree",NULL,NULL,NULL,NULL,"Deer-bin",NULL,NULL,NULL,NULL,NULL,"Bin-ung",NULL,"Meel",NULL,NULL,NULL,"Din-nah","Yill-am",NULL,"Mah-rah",NULL,NULL,NULL,NULL,"Boon","Dah-rang","Dam-boor","Gnaw-run","Moo-roo",NULL,"Boo-yoo","Gee-gah",NULL,"Dee-ah",NULL,NULL,NULL,NULL,NULL,NULL,NULL,"Kill-een","Garm",NULL);	INSERT into bodyparts VALUES ("yuwaalaraay","Baranggal","Bungun","Yuuwirr","Bawa","Murru","Yarray",NULL,NULL,"Mubil","Guway",NULL,NULL,"Buya",NULL,"Buyu","Dhaal",NULL,"Dhaal","Bina","Dhiin","Mil","Ngudjiin","Ngudjiin","Ngulu","Dhina",NULL,"Dhaygal","Maa","Gii",NULL,NULL,NULL,"Dhinbirr","Buyu","Ngaay","Nhun","Muyu",NULL,NULL,"Walarr","Yulay",NULL,"Mabun",NULL,"Bambugal","Dhalay","Yira","Bagurr",NULL,"Bambugal","Dhaygal","Yili");	INSERT into bodyparts VALUES ("pronunciation__yuwaalaraay","Bah-run-gull","Boong-un","You-wid","Bar-wah","Moo-roo","Yah-ray",NULL,NULL,"Moo-bill","Gwoy",NULL,NULL,"Boo-yah",NULL,"Boo-yoo","Darl",NULL,"Darl","Bin-ah","Din","Mill","Nud-jean","Nud-jean","Noo-loo","Din-ah",NULL,"Dah-gull","Mah","Gee",NULL,NULL,NULL,"Din-beer","Boo-yoo","Nah","Noon","Moo-yoo",NULL,NULL,"Wah-lah","You-lay",NULL,"Mah-boon",NULL,"Bum-bah-gull","Dah-lay","Yee-rah","Bah-gurr",NULL,"Bum-bah-gull","Dah-gull","Yill-ee");	INSERT into bodyparts VALUES ("yuwibara","Bumugul",NULL,NULL,NULL,NULL,"Ngunga",NULL,NULL,"Bunna","Gooma",NULL,NULL,"Bulbun",NULL,NULL,NULL,NULL,NULL,"Walloo",NULL,"Dilli",NULL,NULL,NULL,"Dinna",NULL,"Kowno","Mulla",NULL,NULL,NULL,NULL,"Buhn","Toomo",NULL,NULL,"Bootan",NULL,NULL,"Wingara","Bitty","Yirra",NULL,NULL,NULL,"Tallia",NULL,NULL,NULL,NULL,"Kutta",NULL);	INSERT into bodyparts VALUES ("pronunciation__yuwibara","Boom-uh-gull",NULL,NULL,NULL,NULL,"Noong-ah",NULL,NULL,"Boon-ah","Goo-mah",NULL,NULL,"Bull-boon",NULL,NULL,NULL,NULL,NULL,"Wal-loo",NULL,"Dill-ee",NULL,NULL,NULL,"Din-ah",NULL,"Cow-no","Mull-ah",NULL,NULL,NULL,NULL,"Boon","Too-mow",NULL,NULL,"Boo-tun",NULL,NULL,"Win-ah-rah","Bit-tee","Year-ah",NULL,NULL,NULL,"Tar-lee-ah",NULL,NULL,NULL,NULL,"Koot-tah",NULL);
